begin;

create table if not exists public.rate_limits (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  action text not null,
  window_start timestamptz not null,
  count integer not null default 1 check (count >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, action, window_start)
);

create index if not exists idx_rate_limits_window_start
  on public.rate_limits (window_start);

create index if not exists idx_rate_limits_user_action_window
  on public.rate_limits (user_id, action, window_start);

alter table public.rate_limits enable row level security;

drop trigger if exists trg_rate_limits_updated_at on public.rate_limits;
create trigger trg_rate_limits_updated_at
before update on public.rate_limits
for each row
execute function public.update_updated_at_column();

commit;
